### ISSUE TITLE
Conflict/crash with Applied Energistics

### ISSUE THREAD

**Issue by Frobuzmumber** [capnkirok/Voxels#1]
I was attempting to sell some Applied Energistics items to a creeper and the game shut down and then minecraft crashed. The item I shift right clicked was Certus quartz. I have found that there are a few mods that have items that don't show as being sell-able. I will provide a list of those in a seperate post as soon as I compile the list. There will be a mod list provided with this post. (its kind of a large list)

[logs.zip](https://github.com/capnkirok/Voxels/files/429067/logs.zip)
[modlist.txt](https://github.com/capnkirok/Voxels/files/429076/modlist.txt)
[modlist2.txt](https://github.com/capnkirok/Voxels/files/429077/modlist2.txt)

Let me know if you need any other information from this. It was a singleplayer world.

-Frobuzmumber

**Comment by capnkirok** [comment]
If the item doesn't have a recipe then the value is 0... you can always set custom values in the JSON. But that's not the issue here:

Looks like Certus Quartz didn't return an unlocalized name for some strange reason.

Found a solution here, which I will try: https://github.com/pahimar/Equivalent-Exchange-3/commit/438f5121b5c158c6033b0e6b331c8bc276be0921

**Comment by capnkirok** [comment]
Fixed!
