### ISSUE TITLE
No Minecraft trees generating.

### ISSUE THREAD

**Issue by Frobuzmumber** [capnkirok/Voxels#29]
I have found that no minecraft trees seem to generate in the world. I have inventory pet trees, but no minecraft trees. Makes it a bit difficult to obtain wood.

**Comment by capnkirok** [comment]
Yes, that would be a problem. I'll take a look. 1.10 or 1.7.10?

**Comment by Frobuzmumber** [comment]
1.10.2

**Comment by capnkirok** [comment]
Oh my god. I just figured this out.

So my worldgen looks to see if there's a creeper villager loaded in current chunks... if so, it doesn't generate trees ... not good because this is all dependent on view range.

I've set a limit to 50 blocks radius ... which is what it should have been all along.

Anyway fixed now.
